version: '3.8'

services:
  frontend:
    build:
      context: ./frontend-app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    # 백엔드는 이미 루트에 있다고 가정
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:./scm_db.sqlite
